trigger:
- main   # Run when code is pushed to main branch

pool:
  name: Default

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: python hello.py
  displayName: 'Run Hello Python Script'
