# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main   # runs when you push to main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    python3 --version
    python3 hello.py
  displayName: "Run hello.py from GitHub"